package com.lostforstupid.movietracker.utils;

public enum ErrorMessage {

    CAN_NOT_DELETE_MOVIE_NO_SUCH_ID,
    CAN_NOT_UPDATE_MOVIE_NO_SUCH_ID,
    MOVIE_NAME_IS_NULL,
    MOVIE_WAS_NOT_FOUND,
    MOVIE_ALREADY_IN_USER_LIBRARY,
    NO_SUCH_MOVIE_IN_USER_LIBRARY,
    CAN_NOT_UPDATE_STATUS_MOVIE_NOT_FOUND,
    CAN_NOT_ADD_MOVIE_TO_LIBRARY_USER_NOT_FOUND,
    CAN_NOT_ADD_MOVIE_TO_LIBRARY_MOVIE_NOT_FOUND
}
